# Generated by Django 4.2.8 on 2023-12-13 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0004_remove_articles_tests'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Без названия', max_length=255, verbose_name='test_name')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date_of_publication_of_the_test')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.articles')),
            ],
            options={
                'verbose_name': 'Test',
                'verbose_name_plural': 'Tests',
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='Пустой вопрос', verbose_name='article_text')),
                ('type_of_question', models.BooleanField(default=False, verbose_name='has_several_solutions')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.tests')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
            },
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='Пустой ответ', verbose_name='article_text')),
                ('is_right', models.BooleanField(default=False, verbose_name='is_right')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.questions')),
            ],
            options={
                'verbose_name': 'Answer',
                'verbose_name_plural': 'Answers',
            },
        ),
    ]
