# Generated by Django 4.2.8 on 2023-12-13 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tests',
            old_name='question_id',
            new_name='article_id',
        ),
        migrations.AlterField(
            model_name='answers',
            name='text',
            field=models.TextField(default='Пустой ответ', verbose_name='answer_text'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='text',
            field=models.TextField(default='Пустой вопрос', verbose_name='question_text'),
        ),
    ]
