# Generated by Django 4.2.8 on 2023-12-13 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_rename_question_id_tests_article_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='question_id',
            new_name='test_id',
        ),
    ]
